/* Generated By:JavaCC: Do not edit this line. parsernameConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parsernameConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULTIPLY = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int VARNAME = 20;
  /** RegularExpression Id. */
  int LETTER = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int DOUBLE = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int INT_VARNAME = 29;
  /** RegularExpression Id. */
  int BOOL_VARNAME = 30;
  /** RegularExpression Id. */
  int FLOAT_VARNAME = 31;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<INTEGER>",
    "<FLOAT>",
    "<DIGIT>",
    "<VARNAME>",
    "<LETTER>",
    "\";\"",
    "\",\"",
    "\"INT\"",
    "\"FLOAT\"",
    "\"BOOLEAN\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "<INT_VARNAME>",
    "<BOOL_VARNAME>",
    "<FLOAT_VARNAME>",
    "\"(\"",
    "\")\"",
    "\"PROGRAM\"",
    "\"MAIN\"",
    "\"ENDMAIN\"",
    "\"EQB\"",
    "\"NEQB\"",
    "\"EQI\"",
    "\"NEQI\"",
    "\"GEI\"",
    "\"LEI\"",
    "\"GI\"",
    "\"LI\"",
    "\"EQF\"",
    "\"NEQF\"",
    "\"GEF\"",
    "\"LEF\"",
    "\"GF\"",
    "\"LF\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSEIF\"",
    "\"ELSE\"",
    "\"ENDIF\"",
    "\"PRINT(\"",
    "\");\"",
    "\"WHILE\"",
    "\"DO\"",
    "\"ENDWHILE\"",
    "\"PROC\"",
    "\"()\"",
    "\"ENDPROC\"",
    "\"FUNC\"",
  };

}
