/* Generated By:JavaCC: Do not edit this line. parsernameConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parsernameConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULTIPLY = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int VARNAME = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int INT_VARNAME = 18;
  /** RegularExpression Id. */
  int BOOL_VARNAME = 19;
  /** RegularExpression Id. */
  int FLOAT_VARNAME = 20;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<INTEGER>",
    "<FLOAT>",
    "<DIGIT>",
    "<VARNAME>",
    "<LETTER>",
    "<INT_VARNAME>",
    "<BOOL_VARNAME>",
    "<FLOAT_VARNAME>",
    "\"INT\"",
    "\"=\"",
    "\",\"",
    "\";\"",
    "\"BOOLEAN\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"FLOAT\"",
    "\"PROGRAM\"",
    "\"MAIN\"",
    "\"ENDMAIN\"",
    "\"(\"",
    "\")\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"EQB\"",
    "\"NEQB\"",
    "\"EQI\"",
    "\"NEQI\"",
    "\"GEI\"",
    "\"LEI\"",
    "\"GI\"",
    "\"LI\"",
    "\"EQF\"",
    "\"NEQF\"",
    "\"GEF\"",
    "\"LEF\"",
    "\"GF\"",
    "\"LF\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSEIF\"",
    "\"ELSE\"",
    "\"ENDIF\"",
    "\"PRINT(\"",
    "\");\"",
    "\"PROC\"",
    "\"()\"",
    "\"ENDPROC\"",
    "\"FUNC\"",
  };

}
